theme: jekyll-theme-hacker
title: "Peter Kirchner Online v2"
description: "Cloud, Scripting, Coding, Security, Trust - Software Engineer @ Microsoft"
permalink: /:year-:month/:title/
markdown: kramdown
baseurl: /
